   OrderID Customer Region Product  Quantity   Price  OrderDate
0      101    Alice   East  Laptop       1.0  1200.0 2023-01-10
1      102      Bob   West  Tablet       2.0   300.0 2023-01-11
2      103    Alice   East  Laptop       1.0  1200.0 2023-01-12
3      104    David  North  Tablet       3.0   300.0 2023-02-01
4      105      Eva   West  Laptop       2.0  1200.0 2023-02-10
5      106    Frank  North  Tablet       1.0   300.0 2023-02-15
6      107      Eva   West  Laptop       NaN  1200.0 2023-03-01
7      108      Bob   East  Laptop       2.0     NaN 2023-03-05

C:\Users\shriy\AppData\Local\Temp\ipykernel_9616\368687380.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Quantity"].fillna(0, inplace=True)
C:\Users\shriy\AppData\Local\Temp\ipykernel_9616\368687380.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].mean(), inplace=True)

Product  Laptop  Tablet
Region
East        4.0     NaN
North       NaN     4.0
West        2.0     2.0